ATTACH TABLE discover_local
(
    `event_id` UUID, 
    `project_id` UInt64, 
    `type` LowCardinality(String), 
    `timestamp` DateTime, 
    `platform` LowCardinality(String), 
    `environment` LowCardinality(Nullable(String)), 
    `release` LowCardinality(Nullable(String)), 
    `dist` LowCardinality(Nullable(String)), 
    `transaction_name` LowCardinality(String), 
    `message` String, 
    `title` String, 
    `user` String, 
    `user_hash` UInt64, 
    `user_id` Nullable(String), 
    `user_name` Nullable(String), 
    `user_email` Nullable(String), 
    `ip_address_v4` Nullable(IPv4), 
    `ip_address_v6` Nullable(IPv6), 
    `sdk_name` LowCardinality(Nullable(String)), 
    `sdk_version` LowCardinality(Nullable(String)), 
    `http_method` LowCardinality(Nullable(String)), 
    `http_referer` Nullable(String), 
    `tags.key` Array(String), 
    `tags.value` Array(String), 
    `_tags_hash_map` Array(UInt64), 
    `contexts.key` Array(String), 
    `contexts.value` Array(String), 
    `span_id` Nullable(UInt64), 
    `trace_id` Nullable(UUID), 
    `deleted` UInt8
)
ENGINE = Merge('default', '^errors_local$|^transactions_local$')
