ATTACH TABLE errors_local
(
    `project_id` UInt64, 
    `timestamp` DateTime, 
    `event_id` UUID CODEC(NONE), 
    `platform` LowCardinality(String), 
    `environment` LowCardinality(Nullable(String)), 
    `release` LowCardinality(Nullable(String)), 
    `dist` LowCardinality(Nullable(String)), 
    `ip_address_v4` Nullable(IPv4), 
    `ip_address_v6` Nullable(IPv6), 
    `user` String DEFAULT '', 
    `user_hash` UInt64 MATERIALIZED cityHash64(user), 
    `user_id` Nullable(String), 
    `user_name` Nullable(String), 
    `user_email` Nullable(String), 
    `sdk_name` LowCardinality(Nullable(String)), 
    `sdk_version` LowCardinality(Nullable(String)), 
    `http_method` LowCardinality(Nullable(String)), 
    `http_referer` Nullable(String), 
    `tags.key` Array(String), 
    `tags.value` Array(String), 
    `_tags_hash_map` Array(UInt64) MATERIALIZED arrayMap((k, v) -> cityHash64(concat(replaceRegexpAll(k, '(\\=|\\\\)', '\\\\\\1'), '=', v)), tags.key, tags.value), 
    `contexts.key` Array(String), 
    `contexts.value` Array(String), 
    `transaction_name` LowCardinality(String) DEFAULT '', 
    `transaction_hash` UInt64 MATERIALIZED cityHash64(transaction_name), 
    `span_id` Nullable(UInt64), 
    `trace_id` Nullable(UUID), 
    `partition` UInt16, 
    `offset` UInt64 CODEC(DoubleDelta, LZ4), 
    `message_timestamp` DateTime, 
    `retention_days` UInt16, 
    `deleted` UInt8, 
    `group_id` UInt64, 
    `primary_hash` UUID, 
    `hierarchical_hashes` Array(UUID), 
    `received` DateTime, 
    `message` String, 
    `title` String, 
    `culprit` String, 
    `level` LowCardinality(Nullable(String)), 
    `location` Nullable(String), 
    `version` LowCardinality(Nullable(String)), 
    `type` LowCardinality(String), 
    `exception_stacks.type` Array(Nullable(String)), 
    `exception_stacks.value` Array(Nullable(String)), 
    `exception_stacks.mechanism_type` Array(Nullable(String)), 
    `exception_stacks.mechanism_handled` Array(Nullable(UInt8)), 
    `exception_frames.abs_path` Array(Nullable(String)), 
    `exception_frames.colno` Array(Nullable(UInt32)), 
    `exception_frames.filename` Array(Nullable(String)), 
    `exception_frames.function` Array(Nullable(String)), 
    `exception_frames.lineno` Array(Nullable(UInt32)), 
    `exception_frames.in_app` Array(Nullable(UInt8)), 
    `exception_frames.package` Array(Nullable(String)), 
    `exception_frames.module` Array(Nullable(String)), 
    `exception_frames.stack_level` Array(Nullable(UInt16)), 
    `sdk_integrations` Array(String), 
    `modules.name` Array(String), 
    `modules.version` Array(String), 
    `replay_id` Nullable(UUID), 
    INDEX bf_tags_hash_map _tags_hash_map TYPE bloom_filter GRANULARITY 1, 
    INDEX minmax_group_id group_id TYPE minmax GRANULARITY 1, 
    INDEX bf_release release TYPE bloom_filter GRANULARITY 1
)
ENGINE = ReplacingMergeTree(deleted)
PARTITION BY (retention_days, toMonday(timestamp))
ORDER BY (project_id, toStartOfDay(timestamp), primary_hash, cityHash64(event_id))
SAMPLE BY cityHash64(event_id)
TTL timestamp + toIntervalDay(retention_days)
SETTINGS index_granularity = 8192, min_bytes_for_wide_part = 1, enable_vertical_merge_algorithm = 1, min_rows_for_wide_part = 0, ttl_only_drop_parts = 1
