ATTACH TABLE transactions_local
(
    `project_id` UInt64, 
    `event_id` UUID, 
    `trace_id` Nullable(UUID) CODEC(LZ4), 
    `span_id` UInt64, 
    `transaction_name` LowCardinality(String), 
    `transaction_hash` UInt64 MATERIALIZED cityHash64(transaction_name), 
    `transaction_op` LowCardinality(String), 
    `transaction_status` UInt8 DEFAULT 2, 
    `start_ts` DateTime, 
    `start_ms` UInt16, 
    `finish_ts` DateTime, 
    `finish_ms` UInt16, 
    `duration` UInt32, 
    `platform` LowCardinality(String), 
    `environment` LowCardinality(Nullable(String)), 
    `release` LowCardinality(Nullable(String)), 
    `dist` LowCardinality(Nullable(String)), 
    `sdk_name` LowCardinality(String) DEFAULT '', 
    `sdk_version` LowCardinality(String) DEFAULT '', 
    `http_method` LowCardinality(Nullable(String)), 
    `http_referer` Nullable(String), 
    `ip_address_v4` Nullable(IPv4), 
    `ip_address_v6` Nullable(IPv6), 
    `user` String DEFAULT '', 
    `user_hash` UInt64 MATERIALIZED cityHash64(user), 
    `user_id` Nullable(String), 
    `user_name` Nullable(String), 
    `user_email` Nullable(String), 
    `tags.key` Array(String), 
    `tags.value` Array(String), 
    `_tags_hash_map` Array(UInt64) MATERIALIZED arrayMap((k, v) -> cityHash64(concat(replaceRegexpAll(k, '(\\=|\\\\)', '\\\\\\1'), '=', v)), tags.key, tags.value), 
    `contexts.key` Array(String), 
    `contexts.value` Array(String), 
    `_contexts_hash_map` Array(UInt64) MATERIALIZED arrayMap((k, v) -> cityHash64(concat(replaceRegexpAll(k, '(\\=|\\\\)', '\\\\\\1'), '=', v)), contexts.key, contexts.value), 
    `measurements.key` Array(LowCardinality(String)), 
    `measurements.value` Array(Float64), 
    `span_op_breakdowns.key` Array(LowCardinality(String)), 
    `span_op_breakdowns.value` Array(Float64), 
    `spans.op` Array(LowCardinality(String)) TTL finish_ts + toIntervalMonth(1), 
    `spans.group` Array(UInt64) TTL finish_ts + toIntervalMonth(1), 
    `spans.exclusive_time_32` Array(Float32) TTL finish_ts + toIntervalMonth(1), 
    `spans.exclusive_time` Array(Float64) TTL finish_ts + toIntervalMonth(1), 
    `partition` UInt16, 
    `offset` UInt64 CODEC(T64, LZ4), 
    `message_timestamp` DateTime, 
    `retention_days` UInt16, 
    `deleted` UInt8, 
    `type` LowCardinality(String) MATERIALIZED 'transaction', 
    `timestamp` DateTime MATERIALIZED finish_ts, 
    `group_ids` Array(UInt64), 
    `app_start_type` LowCardinality(String), 
    `profile_id` Nullable(UUID), 
    `replay_id` Nullable(UUID), 
    `message` String MATERIALIZED transaction_name, 
    `title` String MATERIALIZED transaction_name, 
    `transaction_source` LowCardinality(String), 
    INDEX minmax_timestamp timestamp TYPE minmax GRANULARITY 1, 
    INDEX minmax_transaction_name transaction_name TYPE minmax GRANULARITY 1, 
    INDEX minmax_transaction_status transaction_status TYPE minmax GRANULARITY 1, 
    INDEX minmax_transaction_op transaction_op TYPE minmax GRANULARITY 1, 
    INDEX minmax_start_ts start_ts TYPE minmax GRANULARITY 1, 
    INDEX minmax_duration duration TYPE minmax GRANULARITY 1, 
    INDEX minmax_event_id event_id TYPE minmax GRANULARITY 1, 
    INDEX minmax_span_id span_id TYPE minmax GRANULARITY 1, 
    INDEX minmax_release release TYPE minmax GRANULARITY 1, 
    INDEX minmax_dist dist TYPE minmax GRANULARITY 1, 
    INDEX minmax_environment environment TYPE minmax GRANULARITY 1, 
    INDEX bf_tags_key tags.key TYPE bloom_filter GRANULARITY 1, 
    INDEX bf_contexts_key contexts.key TYPE bloom_filter GRANULARITY 1, 
    INDEX bf_tags_hash_map _tags_hash_map TYPE bloom_filter GRANULARITY 1, 
    INDEX bf_tags_hash_map_no_fp _tags_hash_map TYPE bloom_filter(0.) GRANULARITY 1, 
    INDEX bf_measurements_key measurements.key TYPE bloom_filter GRANULARITY 1, 
    INDEX bf_span_op_breakdowns_key span_op_breakdowns.key TYPE bloom_filter GRANULARITY 1, 
    INDEX bf_contexts_hash_map _contexts_hash_map TYPE bloom_filter GRANULARITY 1, 
    INDEX bf_spans_op spans.op TYPE bloom_filter() GRANULARITY 1, 
    INDEX bf_spans_group spans.group TYPE bloom_filter() GRANULARITY 1
)
ENGINE = ReplacingMergeTree(deleted)
PARTITION BY (retention_days, toMonday(finish_ts))
ORDER BY (project_id, toStartOfDay(finish_ts), transaction_name, cityHash64(span_id))
SAMPLE BY cityHash64(span_id)
TTL finish_ts + toIntervalDay(retention_days)
SETTINGS index_granularity = 8192
